/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_call */

#ifndef _Included_src_call
#define _Included_src_call
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_call
 * Method:    wallpaperSwap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_src_call_wallpaperSwap
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
